apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
  labels:
    monitoring: kaytu
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      protocol: TCP
      port: 8251
      targetPort: 8251
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051