apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: swagger-ui
spec:
  selector:
    app: swagger-ui
  ports:
  - port: 7255
    targetPort: 7255
  clusterIP: "None"