---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-scheduler
---
apiVersion: v1
kind: Secret
metadata:
  name: scheduler-secret
  annotations:
    kubernetes.io/service-account.name: scheduler
type: kubernetes.io/service-account-token
