apiVersion: v1
kind: Service
metadata:
  name: describe-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    app: describe-scheduler
    monitoring: kaytu
spec:
  selector:
    app: describe-scheduler
  ports:
  - name: http
    port: 5251
    targetPort: 5251
  - name: grpc
    port: 5252
    targetPort: 5252
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: describe-receiver
#  namespace: {{ .Release.Namespace }}
#  labels:
#    app: describe-receiver
#    monitoring: kaytu
#spec:
#  selector:
#    app: describe-receiver
#  ports:
#    - name: http
#      port: 5251
#      targetPort: 5251
#    - name: grpc
#      port: 5252
#      targetPort: 5252
#  clusterIP: "None"
