{{- if eq .Values.keda.enabled true }}
# Job to wait for the CRD to exist
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-crd
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}-wait-for-crd"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: wait-for-crd-sa
      containers:
        - name: wait-for-crd
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for the ScaledObject CRD to be available..."
              until kubectl get crd scaledobjects.keda.sh; do
                echo "ScaledObject CRD not found, retrying in 10 seconds..."
                sleep 10
              done
              echo "ScaledObject CRD found, proceeding with the deployment."
---
{{- end }}