apiVersion: v1
kind: ConfigMap
metadata:
  name: steampipe-service-config
  namespace: {{ .Release.Namespace }}
data:
  aws.spc: |
    connection "aws" {
      plugin = "aws"
      addresses = []
      username = ""
      password = ""
    }

  azure.spc: |
    connection "azure" {
      plugin = "azure"
      addresses = []
      username = ""
      password = ""
    }

  entraid.spc: |
    connection "entraid" {
      plugin = "entraid"
      addresses = []
      username = ""
      password = ""
    }

  opengovernance.spc: |
    connection "opengovernance" {
      plugin = "local/opengovernance"
      addresses = []
      username = ""
      password = ""
      pg_host = "{{ include "postgres.endpoint" . }}"
      pg_port = "{{ include "postgres.port" . }}"
      pg_user = "steampipe_user"
      pg_password = ""
      pg_database = "integration"
      pg_ssl_mode = "{{ include "postgres.sslMode" . }}"
      compliance_service_baseurl = "http://compliance-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
    }
