---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: steampipe
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-steampipe
---
apiVersion: v1
kind: Secret
metadata:
  name: steampipe-secret
  annotations:
    kubernetes.io/service-account.name: steampipe
type: kubernetes.io/service-account-token
