apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-migrator-runner
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-compliance-service-migrator-runner
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: compliance
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-migrator-runner
  apiGroup: rbac.authorization.k8s.io