apiVersion: v1
kind: Secret
metadata:
  name: import-demo-data-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  openSslPassword: MDFaUlBGdU9OMFBNb25P
---
{{- if not (lookup "batch/v1" "Job" .Release.Namespace "import-es-demo-data") -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: import-es-demo-data
  namespace: {{ .Release.Namespace }}
  annotations:
    "app.kubernetes.io/managed-by": "Helm"
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
    helm.sh/resource-policy: keep
    {{- if eq .Values.populateWithSampleData.enabled true }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    {{- end }}
spec:
{{- if eq .Values.populateWithSampleData.enabled false }}
  suspend: true
{{- end }}
  template:
    spec:
      containers:
        - name: import-es-demo-data
          image: "{{ .Values.opengovernance.docker.registry }}/demo-importer-job:{{ .Values.opengovernance.docker.tags.demoImporterJob }}"
          command: ["/demo-importer-worker"]
          env:
{{- include "elastic.envs" . | indent 12 }}
            - name: POSTGRESQL_USERNAME
              value: "{{ include "postgres.masterUser" . }}"
            - name: POSTGRESQL_PASSWORD
              value: "{{ include "postgres.masterPassword" . }}"
            - name: POSTGRESQL_HOST
              value: "{{ include "postgres.endpoint" . }}"
            - name: POSTGRESQL_PORT
              value: "{{ include "postgres.port" . }}"
            - name: DEMO_DATA_S3_URL
              value: "{{ .Values.populateWithSampleData.fileURL }}"
            - name: OPENSSL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: import-demo-data-secret
                  key: openSslPassword
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
---
{{- if not (lookup "batch/v1" "Job" .Release.Namespace "import-psql-demo-data") -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: import-psql-demo-data
  namespace: {{ .Release.Namespace }}
  annotations:
    "app.kubernetes.io/managed-by": "Helm"
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
    "helm.sh/resource-policy": keep
    {{- if eq .Values.populateWithSampleData.enabled true }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    {{- end }}
spec:
{{- if eq .Values.populateWithSampleData.enabled false }}
  suspend: true
{{- end }}
  template:
    spec:
      containers:
        - name: import-psql-demo-data
          image: "{{ .Values.opengovernance.docker.registry }}/import-data-script:{{ .Values.opengovernance.docker.tags.psqlImport }}"
          command: ["/bin/bash", "-c", "/usr/local/bin/import_psql_data.sh"]
          env:
{{- include "elastic.envs" . | indent 12 }}
            - name: POSTGRESQL_USERNAME
              value: "{{ include "postgres.masterUser" . }}"
            - name: POSTGRESQL_PASSWORD
              value: "{{ include "postgres.masterPassword" . }}"
            - name: POSTGRESQL_HOST
              value: "{{ include "postgres.endpoint" . }}"
            - name: POSTGRESQL_PORT
              value: "{{ include "postgres.port" . }}"
            - name: DEMO_DATA_GIT_URL
              value: "https://github.com/kaytu-io/demo-data"
            - name: DEMO_DATA_S3_URL
              value: "{{ .Values.populateWithSampleData.fileURL }}"
            - name: OPENSSL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: import-demo-data-secret
                  key: openSslPassword
      restartPolicy: Never
  backoffLimit: 4
{{- end }}