apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-helmrelease-fullaccess
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - "helm.toolkit.fluxcd.io"
    resources:
      - "helmreleases"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-scheduler-helmrelease-fullaccess
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: scheduler
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-helmrelease-fullaccess
  apiGroup: rbac.authorization.k8s.io