---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-compliance
---
apiVersion: v1
kind: Secret
metadata:
  name: compliance-secret
  annotations:
    kubernetes.io/service-account.name: compliance
type: kubernetes.io/service-account-token
