apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: inventory-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.opengovernance.replicaCount }}
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      serviceAccountName: inventory
      containers:
      - name: inventory-service
        image: "{{ .Values.opengovernance.docker.registry }}/inventory-service:{{ .Values.opengovernance.docker.tags.inventory }}"
        command: ["/inventory-service"]
        imagePullPolicy: Always
        #resources:
        #  limits:
        #    cpu: 1000m
        #    memory: 4Gi
        #  requests:
        #    cpu: 200m
        #    memory: 500Mi
        env:
{{- include "elastic.envs" . | indent 8 }}
        - name: POSTGRESQL_HOST
          value: "{{ include "postgres.endpoint" . }}"

        - name: POSTGRESQL_PORT
          value: "{{ include "postgres.port" . }}"
        - name: POSTGRESQL_USERNAME
          value: "inventory_service"
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: inventoryServiceUserPassword
        - name: POSTGRESQL_DB
          value: "inventory"
        - name: POSTGRESQL_SSLMODE
          value: "{{ include "postgres.sslMode" . }}"
        - name: STEAMPIPE_HOST
          value: steampipe-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: STEAMPIPE_PORT
          value: "9193"
        - name: STEAMPIPE_USERNAME
          value: "steampipe"
        - name: STEAMPIPE_PASSWORD
          value: "abcd"
        - name: STEAMPIPE_DB
          value: "steampipe"
        - name: HTTP_ADDRESS
          value: "0.0.0.0:7251"
        - name: SCHEDULER_BASE_URL
          value: "http://scheduler.{{ .Release.Namespace }}.svc.cluster.local:5251"
        - name: INTEGRATION_BASE_URL
          value: "http://integration-service.{{ .Release.Namespace }}.svc.cluster.local:8000"
        - name: COMPLIANCE_BASE_URL
          value: "http://compliance-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
        - name: METADATA_BASE_URL
          value: "http://metadata-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
        - name: JAEGER_SERVICE_NAME
          value: "inventory-service"
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP