apiVersion: v1
kind: Service
metadata:
  name: es-sink-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: es-sink-service
    monitoring: kaytu
spec:
  selector:
    app: es-sink-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 5252
      targetPort: 5252