apiVersion: apps/v1
kind: Deployment
metadata:
  name: describe-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    app: describe-scheduler
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: describe-scheduler
  template:
    metadata:
      labels:
        app: describe-scheduler
    spec:
      serviceAccountName: scheduler
      containers:
      - name: describe-scheduler
        image: "{{ .Values.opengovernance.docker.registry }}/describe-scheduler-service:{{ .Values.opengovernance.docker.tags.describeSchedulerService }}"
        command: ["/describe-scheduler-service"]
        #resources:
        #  limits:
        #    cpu: 500m
        #    memory: 8Gi
        #  requests:
        #    cpu: 100m
        #    memory: 2Gi
        args:
        - --id=$(SCHEDULER_ID)
        imagePullPolicy: Always
        env:
        - name: NATS_URL
          value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
        - name: HTTP_ADDRESS
          value: "0.0.0.0:5251"
        - name: GRPC_ADDRESS
          value: "0.0.0.0:5252"
        - name: POSTGRESQL_HOST
          value: {{ include "postgres.endpoint" . | quote }}
        - name: POSTGRESQL_PORT
          value: {{ include "postgres.port" . | quote }}
        - name: POSTGRESQL_DB
          value: "describe"
        - name: POSTGRESQL_USERNAME
          value: "describe_scheduler"
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: describeSchedulerUserPassword
        - name: POSTGRESQL_SSLMODE
          value: {{ include "postgres.sslMode" . | quote }}
        - name: SCHEDULER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WORKSPACE_NAME
          value: "main"
        - name: DESCRIBE_INTERVAL_HOURS
          value: "12"
        - name: FULL_DISCOVERY_INTERVAL_HOURS
          value: "48"
        - name: COST_DISCOVERY_INTERVAL_HOURS
          value: "24"
        - name: DESCRIBE_TIMEOUT_HOURS
          value: "12"
        - name: COMPLIANCE_INTERVAL_HOURS
          value: "24"
        - name: QUERY_VALIDATOR_ENABLED
          value: "{{ if .Values.queryvalidator }}{{ default false .Values.queryvalidator.enabled }}{{ else }}false{{ end }}"
        - name: SERVERLESS_PROVIDER
          value: "local"
        - name: COMPLIANCEINTERVALHOURS
          value: "48"
        - name: COMPLIANCE_TIMEOUT_HOURS
          value: "1"
        - name: INSIGHT_INTERVAL_HOURS
          value: "12"
        - name: CHECKUP_INTERVAL_HOURS
          value: "2"
        - name: MUST_SUMMARIZE_INTERVAL_HOURS
          value: "4"
        - name: INVENTORY_BASE_URL
          value: "http://inventory-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
        - name: METADATA_BASE_URL
          value: "http://metadata-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
        - name: COMPLIANCE_BASE_URL
          value: "http://compliance-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
        - name: INTEGRATION_BASE_URL
          value: "http://integration-service.{{ .Release.Namespace }}.svc.cluster.local:8000"
        - name: ESSINK_BASEURL
          value: "http://es-sink-service.{{ .Release.Namespace }}.svc.cluster.local:8000"
        - name: AUTH_GRPC_URI
          value: "auth-service.{{ .Release.Namespace }}.svc.cluster.local:50051"
{{- include "elastic.envs" . | indent 8 }}
        - name: DESCRIBE_JOB_ENDPOINT_LOCAL
          value: "describe-scheduler.{{ .Release.Namespace }}.svc.cluster.local:5252"
        - name: DESCRIBE_DELIVER_ENDPOINT_LOCAL
          value: "es-sink-service.{{ .Release.Namespace }}.svc.cluster.local:5252"
{{/*        - name: DESCRIBE_DELIVER_ENDPOINT_EXTERNAL*/}}
{{/*          value: "{{ .Values.opengovernance.domain.grpc_external }}:443"*/}}

        - name: KMS_ACCOUNT_REGION
          value: "{{ .Values.opengovernance.vault.aws.region }}"
          
        - name: VAULT_PROVIDER
          value: "{{ .Values.opengovernance.vault.provider }}"
        - name: VAULT_AWS_REGION
          value: "{{ .Values.opengovernance.vault.aws.region }}"
        - name: VAULT_AWS_ROLE_ARN
          value: "{{ .Values.opengovernance.vault.aws.roleArn }}"
        - name: VAULT_AWS_ACCESS_KEY
          value: "{{ .Values.opengovernance.vault.aws.accessKey }}"
        - name: VAULT_AWS_SECRET_KEY
          value: "{{ .Values.opengovernance.vault.aws.secretKey }}"
        - name: VAULT_AZURE_BASE_URL
          value: "{{ .Values.opengovernance.vault.azure.baseUrl }}"
        - name: VAULT_AZURE_CLIENT_ID
          value: "{{ .Values.opengovernance.vault.azure.clientId }}"
        - name: VAULT_AZURE_TENANT_ID
          value: "{{ .Values.opengovernance.vault.azure.tenantId }}"
        - name: VAULT_AZURE_CLIENT_SECRET
          value: "{{ .Values.opengovernance.vault.azure.clientSecret }}"
        - name: VAULT_HASHICORP_ADDRESS
          value: "http://{{ .Release.Name }}-vault-internal.{{ .Release.Namespace }}.svc.cluster.local:8200"
        - name: VAULT_KEY_ID
          value: "{{ .Values.opengovernance.vault.keyID }}"

        - name: DO_DELETE_OLD_RESOURCES
          value: "true"
        - name: DO_PROCESS_RECEIVED_MSGS
          value: "true"
        - name: OPERATION_MODE_CONFIG
          value: "scheduler"
        - name: JAEGER_SERVICE_NAME
          value: "describe-scheduler"
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_SAMPLE_RATE
          value: "0.005"
