apiVersion: apps/v1
kind: Deployment
metadata:
  name: rego-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: rego-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.opengovernance.replicaCount }}
  selector:
    matchLabels:
      app: rego-service
  template:
    metadata:
      labels:
        app: rego-service
    spec:
      containers:
      - name: rego-service
        image: "{{ .Values.opengovernance.docker.registry }}/rego-service:{{ .Values.opengovernance.docker.tags.rego }}"
        command: ["/rego-service"]
        imagePullPolicy: Always
        #resources:
        #  limits:
        #    cpu: 500m
        #    memory: 1Gi
        #  requests:
        #    cpu: 500m
        #    memory: 100Mi
        env:
          - name: HTTP_ADDRESS
            value: "0.0.0.0:8000"
{{- include "elastic.envs" . | indent 10 }}
          - name: STEAMPIPE_LOG_LEVEL
            value: "WARN"
          - name: STEAMPIPE_MAX_PARALLEL
            value: "50"
          - name: STEAMPIPE_CACHE
            value: "false"
          - name: STEAMPIPE_UPDATE_CHECK
            value: "false"