apiVersion: v1
kind: Service
metadata:
  name: rego-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: rego-service
    monitoring: kaytu
spec:
  selector:
    app: rego-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000