apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-quick-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: compliance-quick-worker
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: compliance-quick-worker
  template:
    metadata:
      labels:
        app: compliance-quick-worker
    spec:
      containers:
        - name: audit-worker
          image: "{{ .Values.opengovernance.docker.registry }}/audit-job:{{ .Values.opengovernance.docker.tags.complianceQuick }}"
          command: ["/audit-job"]
          args:
            - --id=$(WORKER_ID)
          imagePullPolicy: Always
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: steampipeUserPassword
            - name: METADATA_DB_HOST
              value: "{{ include "postgres.endpoint" . }}"
            - name: METADATA_DB_PORT
              value: "{{ include "postgres.port" . }}"
            - name: METADATA_DB_SSL_MODE
              value: "{{ include "postgres.sslMode" . }}"
            - name: STEAMPIPE_LOG_LEVEL
              value: "WARN"
            - name: STEAMPIPE_MAX_PARALLEL
              value: "50"
            - name: STEAMPIPE_CACHE
              value: "false"
            - name: STEAMPIPE_UPDATE_CHECK
              value: "false"
            - name: NATS_URL
              value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
{{- include "elastic.envs" . | indent 12 }}
            - name: COMPLIANCE_BASEURL
              value: "http://compliance-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
            - name: SCHEDULER_BASEURL
              value: "http://scheduler.{{ .Release.Namespace }}.svc.cluster.local:5251"
            - name: INVENTORY_BASEURL
              value: "http://inventory-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
            - name: METADATA_BASEURL
              value: "http://metadata-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
            - name: ESSINK_BASEURL
              value: "http://es-sink-service.{{ .Release.Namespace }}.svc.cluster.local:8000"

            - name: PROMETHEUS_PUSH_ADDRESS
              value: "prom-system-prometheus-pushgateway.prom-system.svc.cluster.local:9091"

            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_SERVICE_NAME
              value: "audit-worker"
            - name: JAEGER_SAMPLE_RATE
              value: "0.0005"