apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: compliance-quick-worker-scaled-object
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: compliance-quick-worker
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: 1
  maxReplicaCount: {{ .Values.opengovernance.parallelism.complianceQuickJobMaxParallelism}}
  fallback:
    failureThreshold: 1
    replicas: 1
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"
        account: "$G"
        stream: "compliance-quick-run"
        consumer: "compliance-quick-run-service"
        lagThreshold: "1"
        useHttps: "false"