apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-sink-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: es-sink-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.opengovernance.replicaCount }}
  selector:
    matchLabels:
      app: es-sink-service
  template:
    metadata:
      labels:
        app: es-sink-service
    spec:
      containers:
        - name: es-sink-service
          image: "{{ .Values.opengovernance.docker.registry }}/es-sink:{{ .Values.opengovernance.docker.tags.esSink }}"
          command: ["/es-sink-service"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: ESSINK_HTTP__ADDRESS
              value: "0.0.0.0:8000"

            - name: ESSINK_GRPC__ADDRESS
              value: "0.0.0.0:5252"
            - name: ESSINK_GRPC__AUTH_URI
              value: "auth-service.{{ .Release.Namespace }}.svc.cluster.local:50051"

            - name: ESSINK_ELASTICSEARCH__ADDRESS
              value: "https://opensearch-cluster-master.{{ .Release.Namespace }}.svc.cluster.local:9200"
            - name: ESSINK_ELASTICSEARCH__IS_OPEN_SEARCH
              value: "true"
            - name: ESSINK_ELASTICSEARCH__IS_ON_AKS
              value: "true"
            - name: ESSINK_ELASTICSEARCH__USERNAME
              value: "admin"
            - name: ESSINK_ELASTICSEARCH__PASSWORD
              value: "myStrongPassword@123!"
            - name: ESSINK_NATS__URL
              value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
