{{- $workspaceServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $authServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $subscriptionUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $informationUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $schedulerUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $policyServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $complianceServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $coreServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $migratorServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $reporterServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $postgresExporterUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $steampipeUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $alertingServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $integrationServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $taskServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $assistantServiceUserPassword := (randAlpha 16) | b64enc | quote }}
{{- $dexServiceUserPassword  := (randAlpha 16) | b64enc | quote }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace "postgres-secret") }}
{{- if $secret }}
{{- $workspaceServiceUserPassword = index $secret.data "workspaceServiceUserPassword" | default $workspaceServiceUserPassword }}
{{- $authServiceUserPassword = index $secret.data "authServiceUserPassword" | default $authServiceUserPassword }}
{{- $subscriptionUserPassword = index $secret.data "subscriptionUserPassword" | default $subscriptionUserPassword}}
{{- $informationUserPassword = index $secret.data "informationUserPassword" | default $informationUserPassword }}
{{- $schedulerUserPassword = index $secret.data "schedulerUserPassword" | default $schedulerUserPassword }}
{{- $policyServiceUserPassword = index $secret.data "policyServiceUserPassword" | default $policyServiceUserPassword }}
{{- $complianceServiceUserPassword = index $secret.data "complianceServiceUserPassword" | default $complianceServiceUserPassword }}
{{- $coreServiceUserPassword = index $secret.data "coreServiceUserPassword" | default $coreServiceUserPassword }}
{{- $migratorServiceUserPassword = index $secret.data "migratorServiceUserPassword" | default $migratorServiceUserPassword }}
{{- $reporterServiceUserPassword = index $secret.data "reporterServiceUserPassword" | default $reporterServiceUserPassword }}
{{- $postgresExporterUserPassword = index $secret.data "postgresExporterUserPassword" | default $postgresExporterUserPassword }}
{{- $steampipeUserPassword = index $secret.data "steampipeUserPassword" | default $steampipeUserPassword }}
{{- $alertingServiceUserPassword = index $secret.data "alertingServiceUserPassword" | default $alertingServiceUserPassword}}
{{- $integrationServiceUserPassword = index $secret.data "integrationServiceUserPassword" | default $integrationServiceUserPassword}}
{{- $taskServiceUserPassword = index $secret.data "taskServiceUserPassword" | default $taskServiceUserPassword}}
{{- $assistantServiceUserPassword = index $secret.data "assistantServiceUserPassword" | default $assistantServiceUserPassword}}
{{- $dexServiceUserPassword = index $secret.data "dexServiceUserPassword" | default $dexServiceUserPassword}}
{{- end -}}

{{- $issuer := .Values.dex.config.issuer }}
{{- if not $issuer -}}
{{- $issuer = printf "http://%s-dex.%s.svc.cluster.local:5556/dex" .Release.Name .Release.Namespace }}
{{- end }}
{{- $postgres := dict "host" (include "postgres.endpoint" .) "port" (include "postgres.port" . | int) "database" "dex" "user" "dex_service" "password" ($dexServiceUserPassword | replace "\"" "" | b64dec) "ssl" (dict "mode" (include "postgres.sslMode" .)) }}
{{- $config := include "dex.config" . | fromYaml | merge (dict "issuer" $issuer) | merge (dict "storage" (dict "config" $postgres))}}

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  workspaceServiceUserPassword: {{ $workspaceServiceUserPassword }}
  authServiceUserPassword: {{ $authServiceUserPassword }}
  subscriptionUserPassword: {{ $subscriptionUserPassword }}
  informationUserPassword: {{ $informationUserPassword }}
  schedulerUserPassword: {{ $schedulerUserPassword }}
  policyServiceUserPassword: {{ $policyServiceUserPassword }}
  complianceServiceUserPassword: {{ $complianceServiceUserPassword }}
  coreServiceUserPassword: {{ $coreServiceUserPassword }}
  migratorServiceUserPassword: {{ $migratorServiceUserPassword }}
  reporterServiceUserPassword: {{ $reporterServiceUserPassword }}
  postgresExporterUserPassword: {{ $postgresExporterUserPassword }}
  steampipeUserPassword: {{ $steampipeUserPassword }}
  alertingServiceUserPassword: {{ $alertingServiceUserPassword }}
  assistantServiceUserPassword: {{ $assistantServiceUserPassword }}
  dexServiceUserPassword: {{ $dexServiceUserPassword }}
  integrationServiceUserPassword: {{ $integrationServiceUserPassword }}
  taskServiceUserPassword: {{ $taskServiceUserPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dex
type: Opaque
data:
  config.yaml: {{ $config | toYaml | b64enc | quote }}
