apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: metadata-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.opengovernance.replicaCount }}
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      serviceAccountName: metadata
      containers:
      - name: metadata-service
        image: "{{ .Values.opengovernance.docker.registry }}/metadata-service:{{ .Values.opengovernance.docker.tags.metadata }}"
        command: ["/metadata-service"]
        imagePullPolicy: Always
        #resources:
        #  limits:
        #    cpu: 100m
        #    memory: 500Mi
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        env:
        - name: METADATA_POSTGRES__HOST
          value: "{{ include "postgres.endpoint" . }}"
        - name: METADATA_POSTGRES__PORT
          value: "{{ include "postgres.port" . }}"
        - name: METADATA_POSTGRES__DB
          value: "metadata"
        - name: METADATA_POSTGRES__USERNAME
          value: "metadata_service"
        - name: METADATA_POSTGRES__PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: metadataServiceUserPassword
        - name: METADATA_POSTGRES_SSL_MODE
          value: "{{ include "postgres.sslMode" . }}"
        - name: METADATA_HTTP__ADDRESS
          value: "0.0.0.0:6251"
        - name: METADATA_INTEGRATION__BASE_URL
          value: "http://integration-service.%NAMESPACE%.svc.cluster.local:8000"
        - name: METADATA_SCHEDULER__BASE_URL
          value: "http://scheduler.%NAMESPACE%.svc.cluster.local:5251"
        - name: METADATA_COMPLIANCE__BASE_URL
          value: "http://compliance-service.%NAMESPACE%.svc.cluster.local:7251"
        - name: METADATA_INVENTORY__BASE_URL
          value: "http://inventory-service.%NAMESPACE%.svc.cluster.local:7251"
        - name: METADATA_OPENGOVERNANCE_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: METADATA_PRIMARY_DOMAIN_URL
          value: "{{ .Values.global.domain }}"
        - name: METADATA_DEX_GRPC_ADDR
          value: "{{ .Release.Namespace }}-dex.{{ .Release.Namespace }}.svc.cluster.local:5557"
        - name: METADATA_DEX_PUBLIC_CLIENT_REDIRECT_URIS
          value: "https://{{ .Values.global.domain }}/callback,http://{{ .Values.global.domain }}/callback,http://localhost:3000/callback,http://localhost:8080/callback"
        - name: METADATA_DEX_PRIVATE_CLIENT_REDIRECT_URIS
          value: "https://{{ .Values.global.domain }}/callback"
        - name: DEX_PUBLIC_CLIENT_REDIRECT_URIS
          value: "https://{{ .Values.global.domain }}/callback,http://{{ .Values.global.domain }}/callback,http://localhost:3000/callback,http://localhost:8080/callback"
        - name: DEX_PRIVATE_CLIENT_REDIRECT_URIS
          value: "https://{{ .Values.global.domain }}/callback"
        - name: METADATA_SAMPLEDATA_INTEGRATIONS_CHECK
          value: "494894f0-aa87-4c32-bafd-066c3cf1a6ae,545a3e48-559d-4f1c-a446-27882bf77d68,f36afd2f-cd85-47c6-9eff-be8213289d28,218317b1-6f26-4ad0-91a7-40f17311d5b3,49d89218-1109-4b86-a7a4-edb55aa658dd,79302008-5d35-4a83-914c-20ecd80f4228,e6cb0afa-e624-4ca7-8b47-fa9988831137,1c2a6b18-ac87-4f5e-a472-1e26f8704f29,c00bb650-f448-41b7-8ccc-bcd6184f78c3"
        - name: METADATA_VAULT__PROVIDER
          value: {{ .Values.opengovernance.vault.provider }}
        - name: METADATA_VAULT__AWS__REGION
          value: {{ .Values.opengovernance.vault.aws.region }}
        - name: METADATA_VAULT__AWS__ROLE_ARN
          value: {{ .Values.opengovernance.vault.aws.roleArn }}
        - name: METADATA_VAULT__AWS__ACCESS_KEY
          value: {{ .Values.opengovernance.vault.aws.accessKey }}
        - name: METADATA_VAULT__AWS__SECRET_KEY
          value: {{ .Values.opengovernance.vault.aws.secretKey }}
        - name: METADATA_VAULT__AZURE__BASE_URL
          value: {{ .Values.opengovernance.vault.azure.baseUrl }}
        - name: METADATA_VAULT__AZURE__CLIENT_ID
          value: {{ .Values.opengovernance.vault.azure.clientId }}
        - name: METADATA_VAULT__AZURE__TENANT_ID
          value: {{ .Values.opengovernance.vault.azure.tenantId }}
        - name: METADATA_VAULT__AZURE__CLIENT_SECRET
          value: {{ .Values.opengovernance.vault.azure.clientSecret }}
        - name: METADATA_VAULT__HASHICORP__ADDRESS
          value: "http://{{ .Release.Name }}-vault-internal.{{ .Release.Namespace }}.svc.cluster.local:8200"
        - name: METADATA_VAULT__KEY_ID
          value: {{ .Values.opengovernance.vault.keyID }}

        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_SERVICE_NAME
          value: "metadata-service"