---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-metadata
---
apiVersion: v1
kind: Secret
metadata:
  name: metadata-secret
  annotations:
    kubernetes.io/service-account.name: metadata
type: kubernetes.io/service-account-token
