---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.opengovernance.vault.aws.roleArn }}
#    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-integration
---
apiVersion: v1
kind: Secret
metadata:
  name: task-secret
  annotations:
    kubernetes.io/service-account.name: task
type: kubernetes.io/service-account-token