apiVersion: apps/v1
kind: Deployment
metadata:
  name: steampipe-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: steampipe-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.opengovernance.replicaCount }}
  selector:
    matchLabels:
      app: steampipe-service
  template:
    metadata:
      labels:
        app: steampipe-service
    spec:
      serviceAccountName: steampipe
      containers:
      - name: steampipe-service
        image: "{{ .Values.opengovernance.docker.registry }}/steampipe-service:{{ .Values.opengovernance.docker.tags.steampipe }}"
        command: ["steampipe", "service", "start", "--database-listen", "network", "--database-port", "9193", "--database-password", "abcd", "--foreground"]
        imagePullPolicy: Always
        resources:
{{- if eq (.Values.global.size | toString) "xs" }}
          requests:
            cpu: 100m
            memory: 100Mi
{{- else if eq (.Values.global.size | toString) "sm" }}
          requests:
            cpu: 200m
            memory: 4Gi
{{- else if eq (.Values.global.size | toString) "md" }}
          requests:
            cpu: 500m
            memory: 4Gi
{{- else if eq (.Values.global.size | toString) "lg" }}
          requests:
            cpu: 100m
            memory: 1Gi
{{- end }}
        env:
{{- include "elastic.envs" . | indent 10 }}
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: steampipeUserPassword
          - name: CORE_DB_HOST
            value: "{{ include "postgres.endpoint" . }}"
          - name: CORE_DB_PORT
            value: "{{ include "postgres.port" . }}"
          - name: CORE_DB_SSL_MODE
            value: "{{ include "postgres.sslMode" . }}"
          - name: STEAMPIPE_LOG_LEVEL
            value: "DEBUG"
          - name: STEAMPIPE_MAX_PARALLEL
            value: "50"
          - name: STEAMPIPE_CACHE
            value: "false"
          - name: CORE_BASEURL
            value: "http://core-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
        volumeMounts:
#          - name: steampipe-content
#            mountPath: /home/steampipe/.steampipe/
          - name: steampipe-spc
            mountPath: /home/steampipe/.steampipe/config/aws.spc
            subPath: aws.spc
          - name: steampipe-spc
            mountPath: /home/steampipe/.steampipe/config/azure.spc
            subPath: azure.spc
          - name: steampipe-spc
            mountPath: /home/steampipe/.steampipe/config/entraid.spc
            subPath: entraid.spc
          - name: steampipe-spc
            mountPath: /home/steampipe/.steampipe/config/opengovernance.spc
            subPath: opengovernance.spc
      volumes:
        - name: steampipe-spc
          configMap:
            name: steampipe-service-config
#        - name: steampipe-content
#          emptyDir: {}
