apiVersion: v1
kind: Service
metadata:
  name: steampipe-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: steampipe-service
spec:
  selector:
    app: steampipe-service
  ports:
    - name: steampipe
      port: 9193
      targetPort: 9193
    - name: http
      port: 8001
      targetPort: 8001
