apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: post-install-configuration
          image: "{{ .Values.opengovernance.docker.registry }}/post-install-job:{{ .Values.opengovernance.docker.tags.postInstallJob }}"
          command: ["/post-install-job"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 5000Mi
            requests:
              cpu: 100m
              memory: 2000Mi
          env:
{{- include "elastic.envs" . | indent 12 }}
            - name: POSTGRESQL_HOST
              value: "{{ include "postgres.endpoint" . }}"
            - name: POSTGRESQL_PORT
              value: "{{ include "postgres.port" . }}"
            - name: POSTGRESQL_DB
              value: "migrator"
            - name: POSTGRESQL_USERNAME
              value: "migrator_worker"
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: migratorServiceUserPassword
            - name: POSTGRESQL_SSLMODE
              value: "{{ include "postgres.sslMode" . }}"
            - name: STEAMPIPE_HOST
              value: cloudql-service.{{ .Release.Namespace }}.svc.cluster.local
            - name: STEAMPIPE_PORT
              value: "9193"
            - name: STEAMPIPE_DB
              value: "steampipe"
            - name: STEAMPIPE_USERNAME
              value: "steampipe"
            - name: STEAMPIPE_PASSWORD
              value: "abcd"
            - name: STEAMPIPE_SSLMODE
              value: "disable"
            - name: HTTP_ADDRESS
              value: "0.0.0.0:6251"
            - name: ANALYTICS_GIT_URL
              value: "https://github.com/opengovern/platform-configuration"
            - name: CONTROL_ENRICHMENT_GIT_URL
              value: "https://github.com/kaytu-io/control-enrichmentor"
            - name: CORE_BASEURL
              value: "http://core-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
            - name: GITHUB_TOKEN
              value: "{{ .Values.github.token }}"
            - name: PROMETHEUS_PUSH_ADDRESS
              value: "prom-system-prometheus-pushgateway.prom-system.svc.cluster.local:9091"
            - name: IS_MANUAL
              value: "false"
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_SERVICE_NAME
              value: "migrator"
            - name: DEX_GRPC_ADDRESS
              value: "opengovernance-dex.{{ .Release.Namespace }}.svc.cluster.local:5557"
            - name: DEFAULT_DEX_USER_ID
              value: "08a8684b-db88-4b73-90a9-3cd1661f5466"
            - name: DEFAULT_DEX_USER_NAME
              value: "admin"
            - name: DEFAULT_DEX_USER_EMAIL
              value: "admin@opencomply.io"
            - name: DEFAULT_DEX_USER_PASSWORD
              value: "password"

          volumeMounts:
            - name: elasticsearch-index-config
              mountPath: /elasticsearch-index-config
            - name: inventory-data-config
              mountPath: /inventory-data-config

            - name: migrator-config
              mountPath: /core-migration/metadata.json
              subPath: metadata.json
            - name: migrator-config
              mountPath: /core-migration/query_parameters.json
              subPath: query_parameters.json
            - name: migrator-config
              mountPath: /core-migration/chat_prompt.txt
              subPath: chat_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/main_prompt.txt
              subPath: main_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/assets_chat_prompt.txt
              subPath: assets_chat_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/assets_main_prompt.txt
              subPath: assets_main_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/score_chat_prompt.txt
              subPath: score_chat_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/score_main_prompt.txt
              subPath: score_main_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/compliance_chat_prompt.txt
              subPath: compliance_chat_prompt.txt
            - name: migrator-config
              mountPath: /core-migration/compliance_main_prompt.txt
              subPath: compliance_main_prompt.txt
      volumes:
        - name: elasticsearch-index-config
          configMap:
            name: elasticsearch-index-config
        - name: inventory-data-config
          configMap:
            name: inventory-data-config
        - name: migrator-config
          configMap:
            name: migrator-config
  backoffLimit: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrator-config
  namespace: {{ .Release.Namespace }}
data:

  metadata.json: |
    [
      {"key": "workspace_date_time_format", "type": "string", "value": "1900-01-02"},
      {"key": "workspace_debug_mode", "type": "bool", "value": "FALSE"},
      {"key": "workspace_time_window", "type": "string", "value": "30d"},
      {"key": "asset_management_enabled", "type": "bool", "value": "TRUE"},
      {"key": "compliance_enabled", "type": "bool", "value": "TRUE"},
      {"key": "product_management_enabled", "type": "bool", "value": "TRUE"},
      {"key": "allow_invite", "type": "bool", "value": "TRUE"},
      {"key": "workspace_key_support", "type": "bool", "value": "TRUE"},
      {"key": "workspace_max_keys", "type": "int", "value": "3"},
      {"key": "allowed_email_domains", "type": "string", "value": ""},
      {"key": "auto_discovery_method", "type": "string", "value": "scheduled"},
      {"key": "full_discovery_job_interval", "type": "int", "value": "48"},
      {"key": "cost_discovery_job_interval", "type": "int", "value": "24"},
      {"key": "describe_job_interval", "type": "int", "value": "8"},
      {"key": "health_check_job_interval", "type": "int", "value": "60"},
      {"key": "insight_job_interval", "type": "int", "value": "2"},
      {"key": "metrics_job_interval", "type": "int", "value": "2"},
      {"key": "compliance_job_interval", "type": "int", "value": "24"},
      {"key": "data_retention_duration", "type": "int", "value": "366"},
      {"key": "connection_limit", "type": "int", "value": "1000"},
      {"key": "user_limit", "type": "int", "value": "1000"},
      {"key": "analytics_git_url", "type": "string", "value": "https://github.com/opengovern/platform-configuration"},
      {"key": "asset_discovery_aws_policy_arns", "type": "string", "value": "arn:aws:iam::aws:policy/SecurityAudit,arn:aws:iam::aws:policy/ReadOnlyAccess"},
      {"key": "spend_discovery_aws_policy_arns", "type": "string", "value": "arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess"},
      {"key": "asset_discovery_azure_role_ids", "type": "string", "value": "/subscriptions/%s/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7"},
      {"key": "spend_discovery_azure_role_ids", "type": "string", "value": "/subscriptions/%s/providers/Microsoft.Authorization/roleDefinitions/fa23ad8b-c56e-40d8-ac0c-ce449e1d2c64"},
      {"key": "spend_discovery_azure_role_ids", "type": "string", "value": "/subscriptions/%s/providers/Microsoft.Authorization/roleDefinitions/fa23ad8b-c56e-40d8-ac0c-ce449e1d2c64"},
      {"key": "aws_discovery_required_only", "type": "bool", "value": "true"},
      {"key": "azure_discovery_required_only", "type": "bool", "value": "true"},
      {"key": "asset_discovery_enabled", "type": "bool", "value": "true"},
      {"key": "spend_discovery_enabled", "type": "bool", "value": "true"},
      {"key": "customization_enabled", "type": "bool", "value": "true"}
    ]

  chat_prompt.txt: |
    Prompt

  main_prompt.txt: |
    Prompt

  assets_chat_prompt.txt: |
    Prompt

  assets_main_prompt.txt: |
    Prompt

  score_chat_prompt.txt: |
    TODO
  score_main_prompt.txt: |
    Prompt

  compliance_chat_prompt.txt: |
    Prompt

  compliance_main_prompt.txt: |
    Prompt
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-data-config
  namespace: {{ .Release.Namespace }}
data:
  {{- (.Files.Glob "inventory-data/*").AsConfig | nindent 2 }}
