apiVersion: apps/v1
kind: Deployment
metadata:
  name: og-describer-aws
  namespace: {{ .Release.Namespace }}
  labels:
    app: og-describer-aws
spec:
  minReadySeconds: 10
  {{- if eq .Values.keda.enabled true }}
  replicas: 0
  {{- else }}
  replicas: 5
  {{- end }}
  selector:
    matchLabels:
      app: og-describer-aws
  template:
    metadata:
      labels:
        app: og-describer-aws
    spec:
      containers:
        - name: og-describer-aws
          image: "{{ .Values.opengovernance.docker.registry }}/og-describer-aws:{{ .Values.opengovernance.docker.tags.describeWorkerAWS }}"
          command: ["/og-describer-aws"]
          imagePullPolicy: Always
          #resources:
          #  limits:
          #    cpu: 500m
          #    memory: 1Gi
          #  requests:
          #    cpu: 100m
          #    memory: 300Mi
          env:
            - name: NATS_URL
              value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: og-describer-aws-manuals
  namespace: {{ .Release.Namespace }}
  labels:
    app: og-describer-aws-manuals
spec:
  minReadySeconds: 10
  {{- if eq .Values.keda.enabled true }}
  replicas: 0
  {{- else }}
  replicas: 2
  {{- end }}
  selector:
    matchLabels:
      app: og-describer-aws-manuals
  template:
    metadata:
      labels:
        app: og-describer-aws-manuals
    spec:
      serviceAccountName: og-describer-aws
      containers:
        - name: og-describer-aws
          image: "{{ .Values.opengovernance.docker.registry }}/og-describer-aws:{{ .Values.opengovernance.docker.tags.describeWorkerAWS }}"
          command: ["/og-describer-aws"]
          imagePullPolicy: Always
          #resources:
          #  limits:
          #    cpu: 500m
          #    memory: 1Gi
          #  requests:
          #    cpu: 100m
          #    memory: 300Mi
          env:
            - name: NATS_URL
              value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
            - name: MANUAL_TRIGGERS
              value: "true"