---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compliance-summarizer
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-compliance-summarizer
---
apiVersion: v1
kind: Secret
metadata:
  name: compliance-summarizer-secret
  annotations:
    kubernetes.io/service-account.name: compliance-summarizer
type: kubernetes.io/service-account-token
