{{- if eq .Values.keda.enabled true }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: checkup-worker-scaled-object
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkup-worker
    envSourceContainerName: checkup-worker
  pollingInterval: 30
  cooldownPeriod: 300
  idleReplicaCount: 0
  minReplicaCount: 1
  maxReplicaCount: 2
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "{{ .Release.Namespace }}-nats-headless.{{ .Release.Namespace }}.svc.cluster.local:8222"
        account: "$G"
        stream: "checkup"
        consumer: "checkup-service-service"
        lagThreshold: "10"
        useHttps: "false"
---
{{- end }}