---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkup-worker
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-checkup-worker
---
apiVersion: v1
kind: Secret
metadata:
  name: checkup-worker-secret
  namespace: {{ .Release.Namespace }}

  annotations:
    kubernetes.io/service-account.name: checkup-worker
type: kubernetes.io/service-account-token
