apiVersion: v1
kind: Service
metadata:
  name: web-ui-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: web-ui
spec:
  selector:
    app: web-ui
  ports:
  - port: 7298
    targetPort: 7298