apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: inventory-service
    monitoring: kaytu
spec:
  selector:
    app: inventory-service
  ports:
  - name: http
    port: 7251
    targetPort: 7251
