---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-inventory
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
  annotations:
    kubernetes.io/service-account.name: inventory
type: kubernetes.io/service-account-token
