---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-metadata
---
apiVersion: v1
kind: Secret
metadata:
  name: core-secret
  annotations:
    kubernetes.io/service-account.name: core
type: kubernetes.io/service-account-token
