apiVersion: v1
kind: ServiceAccount
metadata:
  name: og-describer-github
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: og-describer-github
  namespace: {{ .Release.Namespace }}
  labels:
    app: og-describer-github
spec:
  minReadySeconds: 10
  {{- if eq .Values.keda.enabled true }}
  replicas: 0
  {{- else }}
  replicas: 5
  {{- end }}
  selector:
    matchLabels:
      app: og-describer-github
  template:
    metadata:
      labels:
        app: og-describer-github
    spec:
      serviceAccountName: og-describer-github
      containers:
        - name: og-describer-azure
          image: "{{ .Values.opengovernance.docker.registry }}/og-describer-github:{{ .Values.opengovernance.docker.tags.describeWorkerGithub }}"
          command: ["/og-describer-github"]
          imagePullPolicy: Always
          #resources:
          #  limits:
          #    cpu: 500m
          #    memory: 1Gi
          #  requests:
          #    cpu: 100m
          #    memory: 300Mi
          env:
            - name: NATS_URL
              value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: og-describer-github-manuals
  namespace: {{ .Release.Namespace }}
  labels:
    app: og-describer-github-manuals
spec:
  minReadySeconds: 10
  {{- if eq .Values.keda.enabled true }}
  replicas: 0
  {{- else }}
  replicas: 2
  {{- end }}
  selector:
    matchLabels:
      app: og-describer-github-manuals
  template:
    metadata:
      labels:
        app: og-describer-github-manuals
    spec:
      serviceAccountName: og-describer-github
      containers:
        - name: og-describer-azure
          image: "{{ .Values.opengovernance.docker.registry }}/og-describer-github:{{ .Values.opengovernance.docker.tags.describeWorkerGithub }}"
          command: ["/og-describer-github"]
          imagePullPolicy: Always
          #resources:
          #  limits:
          #    cpu: 500m
          #    memory: 1Gi
          #  requests:
          #    cpu: 100m
          #    memory: 300Mi
          env:
            - name: NATS_URL
              value: "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.cluster.local:4222"
            - name: MANUAL_TRIGGERS
              value: "true"