apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudql-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloudql-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.opengovernance.replicaCount }}
  selector:
    matchLabels:
      app: cloudql-service
  template:
    metadata:
      labels:
        app: cloudql-service
    spec:
      serviceAccountName: cloudql
      containers:
      - name: cloudql-service
        image: "{{ .Values.opengovernance.docker.registry }}/cloudql-service:{{ .Values.opengovernance.docker.tags.cloudql }}"
        command: ["/bin/bash", "-c",
                  "/cloudql-init-job && steampipe service start --database-listen network --database-port 9193 --database-password abcd --foreground"]
        imagePullPolicy: Always
        resources:
{{- if eq (.Values.global.size | toString) "xs" }}
          requests:
            cpu: 100m
            memory: 100Mi
{{- else if eq (.Values.global.size | toString) "sm" }}
          requests:
            cpu: 200m
            memory: 4Gi
{{- else if eq (.Values.global.size | toString) "md" }}
          requests:
            cpu: 500m
            memory: 4Gi
{{- else if eq (.Values.global.size | toString) "lg" }}
          requests:
            cpu: 100m
            memory: 1Gi
{{- end }}
        env:
{{- include "elastic.envs" . | indent 10 }}
          - name: POSTGRES_HOST
            value: "{{ include "postgres.endpoint" . }}"
          - name: POSTGRES_PORT
            value: "{{ include "postgres.port" . }}"
          - name: POSTGRES_USERNAME
            value: "steampipe_user"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: steampipeUserPassword
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: steampipeUserPassword
          - name: CORE_DB_HOST
            value: "{{ include "postgres.endpoint" . }}"
          - name: CORE_DB_PORT
            value: "{{ include "postgres.port" . }}"
          - name: CORE_DB_SSL_MODE
            value: "{{ include "postgres.sslMode" . }}"
          - name: STEAMPIPE_LOG_LEVEL
            value: "DEBUG"
          - name: STEAMPIPE_MAX_PARALLEL
            value: "50"
          - name: STEAMPIPE_CACHE
            value: "false"
          - name: CORE_BASEURL
            value: "http://core-service.{{ .Release.Namespace }}.svc.cluster.local:6251"
          - name: INTEGRATION_BASEURL
            value: "http://integration-service.{{ .Release.Namespace }}.svc.cluster.local:8000"

