---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudql
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountID }}:role/kaytu-service-{{ .Release.Namespace }}-cloudql
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudql-secret
  annotations:
    kubernetes.io/service-account.name: cloudql
type: kubernetes.io/service-account-token
