apiVersion: v1
kind: Service
metadata:
  name: cloudql-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: cloudql-service
spec:
  selector:
    app: cloudql-service
  ports:
    - name: cloudql
      port: 9193
      targetPort: 9193
