apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: task-service
spec:
  minReadySeconds: 10
  replicas: {{ .Values.opengovernance.replicaCount }}
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      serviceAccountName: task
      containers:
      - name: task-service
        image: "{{ .Values.opengovernance.docker.registry }}/task-service:{{ .Values.opengovernance.docker.tags.tasks }}"
        command: ["/task-service"]
        imagePullPolicy: Always
        #resources:
        #  limits:
        #    cpu: 500m
        #    memory: 1Gi
        #  requests:
        #    cpu: 500m
        #    memory: 100Mi
        env:
        - name: TASKS_POSTGRES__HOST
          value: "{{ include "postgres.endpoint" . }}"
        - name: TASKS_POSTGRES__PORT
          value: "{{ include "postgres.port" . }}"
        - name: TASKS_POSTGRES__DB
          value: "task"
        - name: TASKS_POSTGRES__USERNAME
          value: "postgres"
        - name: TASKS_POSTGRES__PASSWORD
          value: "postgres"
        - name: TASKS_POSTGRES__SSLMODE
          value: "{{ include "postgres.sslMode" . }}"
        - name: TASKS_HTTP__ADDRESS
          value: "0.0.0.0:8001"
        - name: TASKS_INVENTORY__BASE_URL
          value: "http://inventory-service.{{ .Release.Namespace }}.svc.cluster.local:7251"
        - name: TASKS_DESCRIBE__BASE_URL
          value: "http://scheduler.{{ .Release.Namespace }}.svc.cluster.local:5251"
        - name: TASKS_METADATA__BASE_URL
          value: "http://metadata-service.{{ .Release.Namespace }}.svc.cluster.local:6251"

        - name: TASKS_STEAMPIPE__HOST
          value: steampipe-service.{{ .Release.Namespace }}.svc.cluster.local
        - name: TASKS_STEAMPIPE__PORT
          value: "9193"
        - name: TASKS_STEAMPIPE__USERNAME
          value: "steampipe"
        - name: TASKS_STEAMPIPE__PASSWORD
          value: "abcd"
        - name: TASKS_STEAMPIPE__DB
          value: "steampipe"

        - name: TASKS_VAULT__PROVIDER
          value: {{ .Values.opengovernance.vault.provider }}
        - name: TASKS_VAULT__AWS__REGION
          value: {{ .Values.opengovernance.vault.aws.region }}
        - name: TASKS_VAULT__AWS__ROLE_ARN
          value: {{ .Values.opengovernance.vault.aws.roleArn }}
        - name: TASKS_VAULT__AWS__ACCESS_KEY
          value: {{ .Values.opengovernance.vault.aws.accessKey }}
        - name: TASKS_VAULT__AWS__SECRET_KEY
          value: {{ .Values.opengovernance.vault.aws.secretKey }}
        - name: TASKS_VAULT__AZURE__BASE_URL
          value: {{ .Values.opengovernance.vault.azure.baseUrl }}
        - name: TASKS_VAULT__AZURE__CLIENT_ID
          value: {{ .Values.opengovernance.vault.azure.clientId }}
        - name: TASKS_VAULT__AZURE__TENANT_ID
          value: {{ .Values.opengovernance.vault.azure.tenantId }}
        - name: TASKS_VAULT__AZURE__CLIENT_SECRET
          value: {{ .Values.opengovernance.vault.azure.clientSecret }}
        - name: TASKS_VAULT__HASHICORP__ADDRESS
          value: "http://{{ .Release.Name }}-vault-internal.{{.Release.Namespace}}.svc.cluster.local:8200"
        - name: TASKS_VAULT__KEY_ID
          value: {{ .Values.opengovernance.vault.keyID }}

        - name: TASKS_MASTER_ACCESS_KEY
          value: ""
        - name: TASKS_MASTER_SECRET_KEY
          value: ""
        - name: TASKS_JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: TASKS_JAEGER_SERVICE_NAME
          value: "task-service"
        - name: TASKS_JAEGER_SAMPLE_RATE
          value: "0.005"

        - name: CURRENT_NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: KEDA_ENABLED
          value: "{{ .Values.keda.enabled }}"