apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-make-tasks-access
rules:
  - apiGroups:
      - "keda.sh/v1alpha1"
    resources:
      - "scaledobjects"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - "keda.sh"
    resources:
      - "scaledobjects"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - "keda.sh"
    resources:
      - "scaledjobs"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
  - apiGroups:
      - "batch"
    resources:
      - "jobs"
    verbs:
      - "get"
      - "list"
      - "create"
      - "delete"
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-make-tasks-access
subjects:
  - kind: ServiceAccount
    name: task
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-make-tasks-access
  apiGroup: rbac.authorization.k8s.io