apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: task-service
    monitoring: kaytu
spec:
  selector:
    app: task-service
  ports:
  - name: http
    port: 8001
    targetPort: 8001